name: oskarvild
favicon: null
layout_spectrum: 0.7346005530562252
typography_spectrum: 0.8067405305337161
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5832612074445933
  lightness: 0.2546642739325762
  saturation: 0.570831558899954
  rhythmicContrast: 0.15837836475111544
purpose: []
